package com.example.ecomm.Domain;

public class ItemDomain {

    private String name;
    private String imagePath;
    private String price;
    private String description;
    private String category;
    private String location;
    private String id;
    private String sellerId;
    private String sellerName;
    private String sellerPhone;
    private String sellerEmail;
    private String sellerLocation;
    private String sellerImagePath;
    private String sellerRating;
    private String sellerRatingCount;
    private String sellerVerified;
    private String sellerJoinedDate;
    private String sellerLastActive;
    private String sellerTotalAds;
    private String sellerTotalSold;
    private String sellerTotalBought;
    private String sellerTotalRating;
    private String sellerTotalRatingCount;
    private String sellerTotalRatingAverage;
    private String sellerTotalRating1;
    private String sellerTotalRating2;
    private String sellerTotalRating3;
    private String sellerTotalRating4;
    private String sellerTotalRating5;
    private String sellerTotalRating1Count;
    private String sellerTotalRating2Count;
    private String sellerTotalRating3Count;
    private String sellerTotalRating4Count;
    private String sellerTotalRating5Count;
    private String sellerTotalRating1Percent;
    private String sellerTotalRating2Percent;
    private String sellerTotalRating3Percent;
    private String sellerTotalRating4Percent;
    private String sellerTotalRating5Percent;
    private String sellerTotalRating1Average;
    private String sellerTotalRating2Average;
    private String sellerTotalRating3Average;
    private String sellerTotalRating4Average;
    private String sellerTotalRating5Average;
    private String sellerTotalRating1AveragePercent;
    private String sellerTotalRating2AveragePercent;
    private String sellerTotalRating3AveragePercent;
    private String sellerTotalRating4AveragePercent;
    private String sellerTotalRating5AveragePercent;
    private String sellerTotalRating1AveragePercentCount;
    private String sellerTotalRating2AveragePercentCount;
    private String sellerTotalRating3AveragePercentCount;
    private String sellerTotalRating4AveragePercentCount;
    private String sellerTotalRating5AveragePercentCount;
    private String sellerTotalRating1AveragePercentAverage;
    private String sellerTotalRating2AveragePercentAverage;
    private String sellerTotalRating3AveragePercentAverage;
    private String sellerTotalRating4AveragePercentAverage;
    private String sellerTotalRating5AveragePercentAverage;
    private String sellerTotalRating1AveragePercentAverageCount;
   
}
